
import { TodoItem } from '../../../types';

export const INITIAL_POOL_TASKS: TodoItem[] = [
    {
        id: "t-mock0101",
        content: "Complete React Documentation",
        parentId: null,
        goalId: "1",
        planDocId: "p1",
        state: "pool",
        scheduledDate: null,
        expectedFinishAt: null,
        actualFinishAt: null,
        delayDays: null,
        delayReason: null,
        color: "#FFFFFF",
        orderIndex: 0,
        poolOrderIndex: 0,
        waidOrder: null,
        children: []
    },
    {
        id: "t-mock0102",
        content: "Learn Hooks",
        parentId: "t-mock0101",
        goalId: "1",
        planDocId: "p1",
        state: "pool",
        scheduledDate: null,
        expectedFinishAt: null,
        actualFinishAt: null,
        delayDays: null,
        delayReason: null,
        color: "#FFFFFF",
        orderIndex: 0,
        poolOrderIndex: 1,
        waidOrder: null,
        children: []
    },
    {
        id: "t-mock0103",
        content: "Master useEffect",
        parentId: "t-mock0102",
        goalId: "1",
        planDocId: "p1",
        state: "pool",
        scheduledDate: null,
        expectedFinishAt: null,
        actualFinishAt: null,
        delayDays: null,
        delayReason: null,
        color: "#FFFFFF",
        orderIndex: 0,
        poolOrderIndex: 2,
        waidOrder: null,
        children: []
    },
    {
        id: "t-mock0104",
        content: "Understand useContext",
        parentId: "t-mock0102",
        goalId: "1",
        planDocId: "p1",
        state: "pool",
        scheduledDate: null,
        expectedFinishAt: null,
        actualFinishAt: null,
        delayDays: null,
        delayReason: null,
        color: "#FFFFFF",
        orderIndex: 1,
        poolOrderIndex: 3,
        waidOrder: null,
        children: []
    },
    {
        id: "t-mock0201",
        content: "Half Marathon Training: Week 1",
        parentId: null,
        goalId: "2",
        planDocId: "p3",
        state: "pool",
        scheduledDate: null,
        expectedFinishAt: null,
        actualFinishAt: null,
        delayDays: null,
        delayReason: null,
        color: "#FFFFFF",
        orderIndex: 1,
        poolOrderIndex: 4,
        waidOrder: null,
        children: []
    },
    {
        id: "t-mock0202",
        content: "Easy Run 5k",
        parentId: "t-mock0201",
        goalId: "2",
        planDocId: "p3",
        state: "scheduled",
        scheduledDate: "2024-02-10",
        expectedFinishAt: null,
        actualFinishAt: null,
        delayDays: null,
        delayReason: null,
        color: "#FFFFFF",
        orderIndex: 0,
        poolOrderIndex: 5,
        waidOrder: null,
        children: []
    },
    {
        id: "t-mock0203",
        content: "Interval Training",
        parentId: "t-mock0201",
        goalId: "2",
        planDocId: "p3",
        state: "pool",
        scheduledDate: null,
        expectedFinishAt: null,
        actualFinishAt: null,
        delayDays: null,
        delayReason: null,
        color: "#FFFFFF",
        orderIndex: 1,
        poolOrderIndex: 6,
        waidOrder: null,
        children: []
    },
    {
        id: "t-mock0301",
        content: "Buy new running shoes",
        parentId: null,
        goalId: null,
        planDocId: null,
        state: "pool",
        scheduledDate: null,
        expectedFinishAt: null,
        actualFinishAt: null,
        delayDays: null,
        delayReason: null,
        color: "#FFFFFF",
        orderIndex: 2,
        poolOrderIndex: 7,
        waidOrder: null,
        children: []
    }
];
