"""错误码常量。

按模块分组管理。新模块应在尾部追加对应分组，并同步更新
api_error_mapping.py 的 ERROR_CODE_TO_STATUS 映射表。
"""

# ===== 通用错误码 =====
NOT_FOUND = "NOT_FOUND"
CONFLICT = "CONFLICT"
VALIDATION_FAILED = "VALIDATION_FAILED"
INTERNAL_ERROR = "INTERNAL_ERROR"
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

# ===== Habit 模块 =====

HABIT_NOT_FOUND = "HABIT_NOT_FOUND"
CHALLENGE_NOT_FOUND = "CHALLENGE_NOT_FOUND"
CHECKIN_ALREADY_EXISTS = "CHECKIN_ALREADY_EXISTS"
CHECKIN_NOT_FOUND = "CHECKIN_NOT_FOUND"
HABIT_NOT_ACTIVE = "HABIT_NOT_ACTIVE"
BACKFILL_DATE_OUT_OF_WINDOW = "BACKFILL_DATE_OUT_OF_WINDOW"
CANNOT_CANCEL_PAST_CHECKIN = "CANNOT_CANCEL_PAST_CHECKIN"
INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"

CHAIN_NOT_FOUND = "CHAIN_NOT_FOUND"
NODE_NOT_FOUND = "NODE_NOT_FOUND"
CHAIN_VALIDATION_FAILED = "CHAIN_VALIDATION_FAILED"
CHAIN_NODE_VALIDATION_FAILED = "CHAIN_NODE_VALIDATION_FAILED"
REORDER_VALIDATION_FAILED = "REORDER_VALIDATION_FAILED"

# ===== LLM 模块 =====
LLM_RESPONSE_ERROR = "LLM_RESPONSE_ERROR"
LLM_OUTPUT_PARSE_ERROR = "LLM_OUTPUT_PARSE_ERROR"
PROMPT_NOT_FOUND = "PROMPT_NOT_FOUND"

# ===== Repository 模块 =====
ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
ENTITY_ALREADY_EXISTS = "ENTITY_ALREADY_EXISTS"

# ===== Processor 模块 =====
CLASSIFICATION_ERROR = "CLASSIFICATION_ERROR"
CACHE_UPDATE_ERROR = "CACHE_UPDATE_ERROR"

# ===== Config 模块 =====
CONFIG_FILE_NOT_FOUND = "CONFIG_FILE_NOT_FOUND"
INVALID_CONFIG = "INVALID_CONFIG"
