user_name: 默认用户
api_key: null
provider: ''
model: ''
input_tokens_cost: 0.0
output_tokens_cost: 0.0
classification_mode: classify_graph
long_log_threshold: 600
multi_purpose_app_names:
- chrome
- msedge
- firefox
aw_db_path: ~/AppData/Local/activitywatch/activitywatch/aw-server/peewee-sqlite.v2.db
lw_db_path: ~/AppData/Local/lifeprism/data/lifewatch_ai.db
chat_db_path: ~/AppData/Local/lifeprism/data/chat_history.db
data_cleaning_threshold: 10
